const GET_TODO_LOADING = 'GET_TODO_LOADING';
const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
const GET_TODO_ERROR = 'GET_TODO_ERROR';

const ADD_TODO = 'ADD_TODO_SUCCESS';
const ADD_TODO_ERROR = 'ADD_TODO_ERROR';
const ADD_TODO_LOADING = 'ADD_TODO_LOADING';

const CHANGE_TODO = 'CHANGE_TODO';
const CHANGE_TODO_LOADING = 'CHANGE_TODO_LOADING';
const CHANGE_TODO_ERROR = 'CHANGE_TODO_ERROR';

const DELETE_TODO = 'DELETE_TODO';

export {
	GET_TODO_LOADING,
	GET_TODO_SUCCESS,
	GET_TODO_ERROR,
	ADD_TODO_LOADING,
	ADD_TODO,
	ADD_TODO_ERROR,
	CHANGE_TODO,
	CHANGE_TODO_LOADING,
	CHANGE_TODO_ERROR,
	DELETE_TODO
};
